def on_a_pressed():
    global projectile2
    projectile2 = sprites.create_projectile_from_sprite(img("""
            . . . . . . . . 2 . . . . . . . 
                    . . . . . . . . 2 . . . . . . . 
                    . . . . . . . . 2 . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        """),
        mySprite,
        0,
        -50)
    music.pew_pew.play()
    pause(250)


controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def createEnemy(x: number, y: number, t: number):
    global enemiesMap
    myEnemy = None

    if t == 1:
        myEnemy = sprites.create(img("""
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                """),
            SpriteKind.enemy)
        animation.run_image_animation(myEnemy, [
            img("""
                e e e . . . . e e e . . . .
                c d d c . . c d d c . . . .
                c b d d f f d d b c . . . .
                c 3 b d d b d b 3 c . . . .
                f b 3 d d d d 3 b f . . . .
                e d d d d d d d d e . . . .
                e d f d d d d f d e . b f b
                f d d f d d f d d f . f d f
                f b d d b b d d 2 f . f d f
                . f 2 2 2 2 2 2 b b f f d f
                . f b d d d d d d b b d b f
                . f d d d d d b d d f f f .
                . f d f f f d f f d f . . .
                . f f . . f f . . f f . . .
            """),
            img("""
                . . . . . . . . . . . . . .
                e e e . . . . e e e . . . .
                c d d c . . c d d c . . . .
                c b d d f f d d b c . . . .
                c 3 b d d b d b 3 c . . . .
                f b 3 d d d d 3 b f . . . .
                e d d d d d d d d e . . . .
                e d f d d d d f d e b f b .
                f d d f d d f d d f f d f .
                f b d d b b d d 2 b f d f .
                . f 2 2 2 2 2 2 d b d b f .
                . f d d d d d d d f f f . .
                . f d b d f f f d f . . . .
                . . f f f f . . f f . . . .
            """),
                img("""
                    . . . . . . . . . . . . . .
                    e e e . . . . e e e . . . .
                    c d d c . . c d d c . . . .
                    c b d d f f d d b c . . . .
                    c 3 b d d b d b 3 c . . . .
                    f b 3 d d d d 3 b f . . . .
                    e d d d d d d d d e . . . .
                    e d f d d d d f d e . b f b
                    f d d f d d f d d f . f d f
                    f b d d b b d d 2 b f f d f
                    . f 2 2 2 2 2 2 d b b d b f
                    . f d d d d d d d f f f f .
                    . . f d b d f d f . . . . .
                    . . . f f f f f f . . . . .
                """)
        ], 1, True)
        myEnemy.set_position((x + 1) * 20, (y + 1) * 20)
        myEnemy.set_flag(SpriteFlag.BOUNCE_ON_WALL, True)
       
    
    if t == 2:
        myEnemy = sprites.create(img("""
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
        """),
            SpriteKind.enemy)
        animation.run_image_animation(myEnemy, [
            img("""
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f11111111f.......
                ......fd11111111df......
                ......fd11111111df......
                ......fddd1111dddf......
                ......fbdbfddfbdbf......
                ......fcdcf11fcdcf......
                .....ffff111111bf.......
                ....fc111cdb1bdfff......
                ....f1b1bcbfbfc111cf....
                ....fbfbfbffff1b1b1f....
                .........fffffffbfbf....
                ..........fffff.........
                ...........fff..........
                ........................
                ........................
                ........................
                ........................
            """),
            img("""
                ........................
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .....fffc1111111f.......
                ...fc111cd1111111f......
                ...f1b1b1b1111dddf......
                ...fbfbffcf11fcddf......
                ......fcf111111bbf......
                .......ccbdb1b1fcf......
                .......fffbfbfdff.......
                ........ffffffff........
                ........fffffffffff.....
                .........fffffc111cf....
                .........fffff1b1b1f....
                ..........ffffbfbfbf....
                ...........ffff.........
                ........................
                ........................
                ........................
            """),
                img("""
                    ........................
                    ........................
                    ........................
                    ........................
                    ..........ffff..........
                    ........ff1111ff........
                    .......fb111111bf.......
                    .......f11111111f.......
                    ......fd11111111df......
                    ......fdd111111ddf......
                    ......fbdd1111dddf......
                    ......fcdbfddfbdbf......
                    .......fbcf11fcbfff.....
                    .......ffb1111bcfbcf....
                    ........fcdb1bdfbbbf....
                    .......ffffffffffcf.....
                    .....fcb1bcfffff........
                    .....f1b1b1ffff.........
                    ......ffbff.............
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                """)
        ], 1, True)
        myEnemy.set_position((x + 1) * 20, (y + 1) * 20)
        myEnemy.set_flag(SpriteFlag.BOUNCE_ON_WALL, True)
            
    enemies[y * 6 + x] = myEnemy

def on_on_overlap(sprite, projectile):
    global enemiesNum
    for x2 in range(6):
        for y2 in range(4):
            if enemies[y2 * 6 + x2] == sprite:
                sprite.destroy(effects.disintegrate, 10)
                enemies[y2 * 6 + x2] = None
                if enemiesMap[y2 * 6 + x2] == 2:
                    enemiesMap[y2 * 6 + x2] = 1
                    createEnemy(x2, y2, 1) 
                enemiesNum=enemiesNum-1  
                projectile.destroy()
                info.change_score_by(1)
                music.small_crash.play()
                if enemiesNum == 0:
                    game.over(True, effects.confetti)

def on_on_overlap_player(sprite, player):
    game.over(False, effects.melt)

sprites.on_overlap(SpriteKind.enemy, SpriteKind.projectile, on_on_overlap)
sprites.on_overlap(SpriteKind.enemy, SpriteKind.player, on_on_overlap_player)

step_y = 0
flag = False
step_x = 0
enemies: List[Sprite] = []
myEnemy: Sprite = None
projectile2: Sprite = None
mySprite: Sprite = None
myEnemy2 = None
speed = 0
step = 2
enemiesNum=30

enemiesMap = [2, 2, 2, 2, 2, 2, 
              2, 2, 2, 2, 2, 2, 
              1, 1, 1, 1, 1, 1,
              0, 0, 0, 0, 0, 0]

mySprite = sprites.create(img("""
        . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . c c . . . . . . . 
            . . . . . . . 5 5 . . . . . . . 
            . . . . . . . c c . . . . . . . 
            . . . . . . . 5 5 . . . . . . . 
            . . . . . . . c c . . . . . . . 
            . . . . . . e e e e . . . . . . 
            . . . . . . e e e e . . . . . . 
            . . . . . e e e e e e . . . . . 
            . . . . e e c c c c e e . . . . 
            . . e e e c c c c c c e e e . . 
            . . e e e e c c c c e e e e . . 
            . . e e e e e e e e e e e e . . 
            . . . . . e e e e e e . . . . .
    """),
    SpriteKind.player)
controller.move_sprite(mySprite, 50, 0)
mySprite.set_position(76, 122)
mySprite.set_flag(SpriteFlag.BOUNCE_ON_WALL, True)

for x22 in range(6):
    for y22 in range(4):
        createEnemy(x22, y22, enemiesMap[y22*6 + x22])

def on_update_interval():
    global step_x, flag, step, step_y
    step_x = step_x + step
    flag = True
    y23 = 0
    while y23 < 4 and flag:
        x23 = 0
        while x23 < 6 and flag:
            if enemies[y23 * 6 + x23] != None:
                if (x23 + 1) * 20 + step_x > 140 or (x23 + 1) * 20 + step_x < 20:
                    step = step * -1
                    step_y = step_y + 4
                    music.zapped.play()
                    flag = False
            x23 += 1
        y23 += 1
    y23 = 0
    while y23 < 4:
        x23 = 0
        while x23 < 6:
            if enemies[y23 * 6 + x23] != None:
                enemies[y23 * 6 + x23].set_position((x23 + 1) * 20 + step_x, (y23 + 1) * 20 + step_y)
            x23 += 1
        y23 += 1

game.on_update_interval(50, on_update_interval)
